services:
  web-rtc-stream: 
    build:
      dockerfile:
        stream.Dockerfile
    devices: 
      - /dev/video${DEVICE}:/dev/video${DEVICE}
    network_mode: "host"
  web:
    build: 
      dockerfile:
        web.Dockerfile
      args:
        - DEVICE=${DEVICE}
    network_mode: "host"
